### ISSUE TITLE
RuntimeError: The expanded size of the tensor (1) must match the existing size (64) at non-singleton dimension 3.  Target sizes: [2, 1, 1, 1].  Tensor sizes: [2, 128, 64, 64] (inferExpandGeometry at /pytorch/aten/src/ATen/ExpandUtils.cpp:75)

### ISSUE THREAD

**Issue by wangy9711** [princeton-vl/CornerNet-Lite#10]
Hey, thanks for your work.
I want to try your net, I did create the conda environment. But when I execute ```python demo.py```:
![image](https://user-images.githubusercontent.com/45476795/56471015-e8bf8300-647f-11e9-9ca5-8caf475409f4.png)

I only have one GPU, RTX2080.
Waiting for your suggestions.

**Comment by heilaw** [comment]
It may have something to do with the compilation of the corner pooling layers. Were you using GCC 4.9.2 or above to compile the layers?

**Comment by wangy9711** [comment]
> It may have something to do with the compilation of the corner pooling layers. Were you using GCC 4.9.2 or above to compile the layers?

My gcc version is 5.4.0, Ubuntu version is 16.04.

**Comment by owen800q** [comment]
> > It may have something to do with the compilation of the corner pooling layers. Were you using GCC 4.9.2 or above to compile the layers?
> 
> My gcc version is 5.4.0, Ubuntu version is 16.04.



> > It may have something to do with the compilation of the corner pooling layers. Were you using GCC 4.9.2 or above to compile the layers?
> 
> My gcc version is 5.4.0, Ubuntu version is 16.04.

I encountered this problem too before, it works perfectly when I upgraded it to ubuntu 18.04

**Comment by wangy9711** [comment]
I find the solution by following [change <torch/torch.h> to <torch/extension.h>](https://github.com/princeton-vl/CornerNet-Lite/pulls).
After did that, I can get the result.
Thanks!
