### ISSUE TITLE
How to detect only one class and output the result

### ISSUE THREAD

**Issue by ericwang321** [princeton-vl/CornerNet-Lite#105]
1. 

`How to detect multiple images at the same time?`

2. 

`The test result only exports the text result (txt file)?`

3. 

`The type of detection is only a specific class, such as a person?`

thanks for any suggestion

**Comment by heilaw** [comment]
1. Our current implementation does not support batch inference.
2. No. You can use the demo script to get the boxes in a dictionary.
3. I am not sure if I understand this question correctly. The detector can detect objects of 80 classes.

**Comment by ericwang321** [comment]
Thank you for your reply @heilaw 
The  question is:
How to detect only a single class, such as a person?

**Comment by ericwang321** [comment]
Close issue temporarily
