### ISSUE TITLE
how to calculate  mean, std eigenvalue and eigenvector?

### ISSUE THREAD

**Issue by dawnknight** [princeton-vl/CornerNet-Lite#106]
#36 
Hi, Just want to know those parameters are calculated from entire images or just the bounding boxes in those images? Also the 3 components in the mean and std corresponding to the three channels of the image? Thanks

**Comment by heilaw** [comment]
We randomly selected 5000 images from COCO and calculated the parameters from entire images. The 3 components correspond to the BGR channels.

**Comment by anurag1paul** [comment]
This link provides a tutorial for calculating eigen-values and eigen vectors.
https://deshanadesai.github.io/notes/Fancy-PCA-with-Scikit-Image

**Comment by dawnknight** [comment]
thanks :)
