### ISSUE TITLE
The speed of training is slower when I use more gpus

### ISSUE THREAD

**Issue by Jack-Cherish** [princeton-vl/CornerNet-Lite#110]
Thanks for your nice work.

I meet one issue that the speed of training is lowser when I use more gpus.

I trained CornerNet-Squeeze and the training took around 91 hours when I used one gpu.
![64311296-36bfc800-cfd6-11e9-9c79-e068730103ae](https://user-images.githubusercontent.com/16872370/64322309-e9068800-cff4-11e9-826f-42d35299f698.png)
![64314242-e863f680-cfe0-11e9-9337-da57fb7ed02f](https://user-images.githubusercontent.com/16872370/64322320-ed32a580-cff4-11e9-92a5-188e7fe9fe84.png)

I trained CornerNet-Squeeze and the training took around 113 hours when I used four gpus.
![64314358-57d9e600-cfe1-11e9-910c-18c5d51249f5](https://user-images.githubusercontent.com/16872370/64322511-48fd2e80-cff5-11e9-9225-5b88fbb97458.png)
![64314367-5c9e9a00-cfe1-11e9-941e-e803ab56a0b7](https://user-images.githubusercontent.com/16872370/64322428-223ef800-cff5-11e9-83fc-864ef9f72246.png)

It will take around 156 hours if I train CornerNet-Squeeze with eight gpus.

I try to increase the number of prefetch_size in CornerNet-Squeeze.json to get more training_queue for loading dataset, but it\`s useless.

I also try to increase the number of workers, it does\`t work either.

What should I do to solve this problem?

Look forward to your reply.

**Comment by Jack-Cherish** [comment]
Have replied in e-mail.

**Comment by MurrayC7** [comment]
> Have replied in e-mail.

I have the same problem as you do. Could you please tell me the solution? Thank you :)

**Comment by Jack-Cherish** [comment]
> > Have replied in e-mail.
> 
> I have the same problem as you do. Could you please tell me the solution? Thank you :)

FYI.
![MacHi 2019-12-04 15-22-06](https://user-images.githubusercontent.com/16872370/70121584-dc540780-16a9-11ea-98ea-a4c12044a293.png)

**Comment by MurrayC7** [comment]
@Jack-Cherish Okay, thank you.
