### ISSUE TITLE
How to change backbone

### ISSUE THREAD

**Issue by gonghaotian** [princeton-vl/CornerNet-Lite#129]
I'd like to change the backbone to another architecture
but I did not find the code of this part
how to change the architecture of backbone?
thanks~
@heilaw

**Comment by heilaw** [comment]
The network architecture is defined [here](https://github.com/princeton-vl/CornerNet-Lite/blob/master/core/models/CornerNet_Saccade.py).

**Comment by gonghaotian** [comment]
@heilaw thank u for ur reply 
i have another problem when i test my model
the model can be tested on coco val2014 with 38mAP and i think the result is acceptable because some of my training details
but when i test on coco test2017，mAP are all -1，i dont know the meaning of -1 ，i googled this but find nothing
thanks a lot!

**Comment by gonghaotian** [comment]
btw，issue#120 meet the same problem like mine
