### ISSUE TITLE
Train with customed dataset

### ISSUE THREAD

**Issue by ray-lee-94** [princeton-vl/CornerNet-Lite#14]
I want to tran the model for my dataset which has 9 categories.
I  just modify the  coco.py for the data. Beside I set the CornerNet_Saccade.py 
```python
	#TODO 80_>9
        tl_heats = nn.ModuleList([self._pred_mod(9) for _ in range(stacks)])
        br_heats = nn.ModuleList([self._pred_mod(9) for _ in range(stacks)])
```
So how to use your pretrained model for the train process ?

**Comment by heilaw** [comment]
1. Run `python train.py CornerNet_Saccade --initialize` to generate a randomly initialized model, which will be saved to `cache/nnet/CornerNet_Saccade/CornerNet_Saccade_0.pkl`.
2. Copy the parameters from the trained model to randomly initialized model except the `{tl,br}_heats` layers. The model is a Python dictionary where the keys are the parameter names and the values are the parameters. So you can easily filter out the parameters for the `{tl,br}_heats` layers.
3. Save the model as `CornerNet_Saccade_pretrained.pkl`
4. Add `"pretrain": "/path/to/your/pretrained/model"` in the `db` section of `configs/CornerNet_Saccade.json`.
5. Start the training `python train.py CornerNet_Saccade`.

You may want to checkout the save and load functions in PyTorch.

**Comment by jerryxucheng** [comment]
@VCBE123  I'm a new comer in machine learning. May I ask where to modify in the coco.py to adapt the model to a dataset with different numbers of categories?

**Comment by ray-lee-94** [comment]
> @VCBE123 I'm a new comer in machine learning. May I ask where to modify in the coco.py to adapt the model to a dataset with different numbers of categories?

you need to change  "_coco_cls_ids", "_coco_cls_names",and the path to your dataset

**Comment by jerryxucheng** [comment]
@VCBE123 I have already changed ids and names. The question is that the dataset is generated by label me, which gives me hundreds of json files.  When I point to a certain json file, there is an error:
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main(None, ngpus_per_node, args)
  File "train.py", line 220, in main
    training_dbs = [datasets[dataset](config["db"], split=train_split, sys_config=system_config) for _ in range(workers)]
  File "train.py", line 220, in <listcomp>
    training_dbs = [datasets[dataset](config["db"], split=train_split, sys_config=system_config) for _ in range(workers)]
  File "/home/deepvision/xc/CornerNet-Lite/core/dbs/coco.py", line 49, in __init__
    self._detections, self._eval_ids = self._load_coco_annos()
  File "/home/deepvision/xc/CornerNet-Lite/core/dbs/coco.py", line 59, in _load_coco_annos
    class_ids = coco.getCatIds()
  File "/home/deepvision/anaconda3/lib/python3.6/site-packages/pycocotools/coco.py", line 170, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'
So how to solve the problem? Thank you a lot.

**Comment by ray-lee-94** [comment]
You need to format your dataset to the coco-stytle.

**Comment by gtwell** [comment]
how to use pascal_voc dataset training?

**Comment by cwjhx** [comment]
> 1. Run `python train.py CornerNet_Saccade --initialize` to generate a randomly initialized model, which will be saved to `cache/nnet/CornerNet_Saccade/CornerNet_Saccade_0.pkl`.
> 2. Copy the parameters from the trained model to randomly initialized model except the `{tl,br}_heats` layers. The model is a Python dictionary where the keys are the parameter names and the values are the parameters. So you can easily filter out the parameters for the `{tl,br}_heats` layers.
> 3. Save the model as `CornerNet_Saccade_pretrained.pkl`
> 4. Add `"pretrain": "/path/to/your/pretrained/model"` in the `db` section of `configs/CornerNet_Saccade.json`.
> 5. Start the training `python train.py CornerNet_Saccade`.
> 
> You may want to checkout the save and load functions in PyTorch.

I don't understand here：
2. Copy the parameters from the trained model to randomly initialized model except the `{tl,br}_heats` layers. The model is a Python dictionary where the keys are the parameter names and the values are the parameters. So you can easily filter out the parameters for the `{tl,br}_heats` layers.

**Comment by cwjhx** [comment]
> > @VCBE123 I'm a new comer in machine learning. May I ask where to modify in the coco.py to adapt the model to a dataset with different numbers of categories?
> 
> you need to change "_coco_cls_ids", "_coco_cls_names",and the path to your dataset

【 "categories": 80,】 in the db section of configs/CornerNet_Saccade.json。Do you need to change？

**Comment by jianyin2016** [comment]
I have no idea why it doesn't work with testing but during training it works well as to **my own dataset**.

I successfully finished training and testing with CornerNet_Squezze on coco, but as to my own dataset,:
firstly I have done the midification as same as @VCBE123 (besides I change tag_len as  my dataset is dense of objects ) ;
secondly I transform my dataset to coco style, and fix the PATH setup；
thirdly, the training goes on well；
then I try to evaluate the checkpiont file I got, and come up with a question,details as following:
**_RuntimeError: Error(s) in loading state_dict for DummyModule:
	size mismatch for module.tl_heats.0.1.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
	size mismatch for module.tl_heats.0.1.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for module.tl_heats.1.1.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
	size mismatch for module.tl_heats.1.1.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for module.br_heats.0.1.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
	size mismatch for module.br_heats.0.1.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for module.br_heats.1.1.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
	size mismatch for module.br_heats.1.1.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80])._**

@heilaw 
yj.

**Comment by pingqi** [comment]
@VCBE123 @heilaw 
how to copy the param from one A pkl to another B pkl?The process is only forward? when get the B pkl ,then using train.py to train?

2. Copy the parameters from the trained model to randomly initialized model except the {tl,br}_heats layers. The model is a Python dictionary where the keys are the parameter names and the values are the parameters. So you can easily filter out the parameters for the {tl,br}_heats layers.
