### ISSUE TITLE
Baidu Cloud Data Sharing  CornerNet-Lite数据集 百度云数据集分享。

### ISSUE THREAD

**Issue by QQ2737499951** [princeton-vl/CornerNet-Lite#18]
CornerNet-Lite数据集
链接：https://pan.baidu.com/s/141G-JZuF2EHypJwIgbicbw 
提取码：7z3k 
 
 **CornerNet_Squeeze_500000.pkl (122M)
 CornerNet_Saccade_500000.pkl (447M) 
 CornerNet_500000.pkl (768M)
annotations.zip(157.5M)
** 

Put the CornerNet-Saccade model under <CornerNet-Lite dir>/cache/nnet/CornerNet_Saccade/, CornerNet-Squeeze model under <CornerNet-Lite dir>/cache/nnet/CornerNet_Squeeze/ and CornerNet model under <CornerNet-Lite dir>/cache/nnet/CornerNet/. (* Note we use underscore instead of dash in both the directory names for CornerNet-Saccade and CornerNet-Squeeze.)

==========
将CornerNet-Saccade模型放在下面<CornerNet-Lite dir>/cache/nnet/CornerNet_Saccade/，将CornerNet-Squeeze模型放在下面<CornerNet-Lite dir>/cache/nnet/CornerNet_Squeeze/，使用CornerNet模型<CornerNet-Lite dir>/cache/nnet/CornerNet/。（*注意我们在CornerNet-Saccade和CornerNet-Squeeze的目录名中使用下划线而不是破折号。）

注意：CornerNet模型与原始CornerNet存储库中的模型相同。我们刚将它移植到这个新的仓库。

**Comment by sunshangyun** [comment]
thanks
