### ISSUE TITLE
What's the time consumed to train CornerNet-Saccade with hourglasses-54 backbone on coco dataset?

### ISSUE THREAD

**Issue by auroua** [princeton-vl/CornerNet-Lite#25]

**Comment by heilaw** [comment]
It took around two and a half week to train with 4 1080Ti GPUs.

**Comment by auroua** [comment]
Thanks

**Comment by liminghuiv** [comment]
Hi @heilaw since it took so long to train. is there any tool to monitor the training process.

**Comment by xiaozhuka** [comment]
@auroua Hi, do you know how to change the backbone hourglass 52 and hourglass 104?
