### ISSUE TITLE
how to calculate ae_loss ?

### ISSUE THREAD

**Issue by gtwell** [princeton-vl/CornerNet-Lite#37]
In losses.py,  when calcalating ae_loss, the push loss mentioned as:

> dist = dist - 1 / (num + 1e-4)

I couldn't understand it? If you want to subtract the j=k in the formula, may be not use this method?
Looking forward your reply. thks

**Comment by wjpjet** [comment]
I saw the same issue, it is explained here: https://github.com/princeton-vl/CornerNet/issues/51
