### ISSUE TITLE
physical meaning of 'gaussian_radius'

### ISSUE THREAD

**Issue by shuxp** [princeton-vl/CornerNet-Lite#47]
In core/sample/util.py, there is a funtion called 'gaussian_radius'. 

It can dynamic choose the radius of gaussian heatmap.

But I can't understand what does it mean. 

Could you pls give me some advices? Thanks a lot.

**Comment by heilaw** [comment]
The points that are within a radius of the ground-truth locations can still generate bounding boxes that have large overlaps with the ground-truth bounding boxes. So we want to penalize those points less. The radius is determined such that the points within the radius can generate bounding boxes above certain IoU threshold. You can find more details in our CornerNet [paper](https://arxiv.org/abs/1808.01244).

**Comment by shuxp** [comment]
> The points that are within a radius of the ground-truth locations can still generate bounding boxes that have large overlaps with the ground-truth bounding boxes. So we want to penalize those points less. The radius is determined such that the points within the radius can generate bounding boxes above certain IoU threshold. You can find more details in our CornerNet [paper](https://arxiv.org/abs/1808.01244).

Yeap, but how to choose the radius? In core/sample/util.py,
```
if gaussian_rad == -1:
      radius = gaussian_radius((height, width), gaussian_iou)
      radius = max(0, int(radius))
else:
       radius = gaussian_rad
```
the 'else' path choose the radius manually, but the 'if' path use gaussion_radius to dynamic choose the radius. In fact, I can't figure out what 'gaussian_radius' function mean actually.

It seems a solution of a quadratic equation, and choose the min value. 
what does the  quadratic equation mean? 
Could you pls give me some clues?

```
def gaussian_radius(det_size, min_overlap):
    height, width = det_size

    a1  = 1
    b1  = (height + width)
    c1  = width * height * (1 - min_overlap) / (1 + min_overlap)
    sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)
    r1  = (b1 - sq1) / (2 * a1)

    a2  = 4
    b2  = 2 * (height + width)
    c2  = (1 - min_overlap) * width * height
    sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)
    r2  = (b2 - sq2) / (2 * a2)

    a3  = 4 * min_overlap
    b3  = -2 * min_overlap * (height + width)
    c3  = (min_overlap - 1) * width * height
    sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)
    r3  = (b3 + sq3) / (2 * a3)
    return min(r1, r2, r3)
```

**Comment by gtwell** [comment]
> > The points that are within a radius of the ground-truth locations can still generate bounding boxes that have large overlaps with the ground-truth bounding boxes. So we want to penalize those points less. The radius is determined such that the points within the radius can generate bounding boxes above certain IoU threshold. You can find more details in our CornerNet [paper](https://arxiv.org/abs/1808.01244).
> 
> Yeap, but how to choose the radius? In core/sample/util.py,
> 
> ```
> if gaussian_rad == -1:
>       radius = gaussian_radius((height, width), gaussian_iou)
>       radius = max(0, int(radius))
> else:
>        radius = gaussian_rad
> ```
> 
> the 'else' path choose the radius manually, but the 'if' path use gaussion_radius to dynamic choose the radius. In fact, I can't figure out what 'gaussian_radius' function mean actually.
> 
> It seems a solution of a quadratic equation, and choose the min value.
> what does the quadratic equation mean?
> Could you pls give me some clues?
> 
> ```
> def gaussian_radius(det_size, min_overlap):
>     height, width = det_size
> 
>     a1  = 1
>     b1  = (height + width)
>     c1  = width * height * (1 - min_overlap) / (1 + min_overlap)
>     sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)
>     r1  = (b1 - sq1) / (2 * a1)
> 
>     a2  = 4
>     b2  = 2 * (height + width)
>     c2  = (1 - min_overlap) * width * height
>     sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)
>     r2  = (b2 - sq2) / (2 * a2)
> 
>     a3  = 4 * min_overlap
>     b3  = -2 * min_overlap * (height + width)
>     c3  = (min_overlap - 1) * width * height
>     sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)
>     r3  = (b3 + sq3) / (2 * a3)
>     return min(r1, r2, r3)
> ```

hello, have you understood the function of `gaussian_radius`?

**Comment by gtwell** [comment]
for `r2` you can calulate as following formula:
![6ff0f58b-74cc-4637-bbb9-1ea3aec26cdc](https://user-images.githubusercontent.com/27282516/59024894-81ba2a00-8885-11e9-85a3-6f861eda715f.jpg)

**Comment by shuxp** [comment]
> for `r2` you can calulate as following formula:
> ![6ff0f58b-74cc-4637-bbb9-1ea3aec26cdc](https://user-images.githubusercontent.com/27282516/59024894-81ba2a00-8885-11e9-85a3-6f861eda715f.jpg)

so what is the mean of iou? how to measure iou with gauss heat map?

**Comment by shuxp** [comment]
@gtwell In my mind, r1,r2,r3 are three solution to three quadratic equation. If we draw these formula, we will find min(r1,r2,r3) will not be in [0, min(h,w)/2] and with increasing iou, the r will be smaller. These are our final result. But what is the mean for iou and how to calculate it, that is a question.

**Comment by gtwell** [comment]
@shuxp iou我这里指的是`min_overlap`，这个是人为指定的，在论文中它的值为0.3
```python
def gaussian_radius(det_size, min_overlap):
    height, width = det_size

    a1  = 1
    b1  = (height + width)
    c1  = width * height * (1 - min_overlap) / (1 + min_overlap)
    sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)
    r1  = (b1 - sq1) / (2 * a1)

    a2  = 4
    b2  = 2 * (height + width)
    c2  = (1 - min_overlap) * width * height
    sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)
    r2  = (b2 - sq2) / (2 * a2)

    a3  = 4 * min_overlap
    b3  = -2 * min_overlap * (height + width)
    c3  = (min_overlap - 1) * width * height
    sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)
    r3  = (b3 + sq3) / (2 * a3)
    return min(r1, r2, r3)
```

**Comment by shuxp** [comment]
> @shuxp iou我这里指的是`min_overlap`，这个是人为指定的，在论文中它的值为0.3
> 
> ```python
> def gaussian_radius(det_size, min_overlap):
>     height, width = det_size
> 
>     a1  = 1
>     b1  = (height + width)
>     c1  = width * height * (1 - min_overlap) / (1 + min_overlap)
>     sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)
>     r1  = (b1 - sq1) / (2 * a1)
> 
>     a2  = 4
>     b2  = 2 * (height + width)
>     c2  = (1 - min_overlap) * width * height
>     sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)
>     r2  = (b2 - sq2) / (2 * a2)
> 
>     a3  = 4 * min_overlap
>     b3  = -2 * min_overlap * (height + width)
>     c3  = (min_overlap - 1) * width * height
>     sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)
>     r3  = (b3 + sq3) / (2 * a3)
>     return min(r1, r2, r3)
> ```

是的，那这个overlap算的是那两个形状的overlap呢？

**Comment by gtwell** [comment]
@shuxp 里面阴影部分的面积和一个ground truth框面积的overlap这个时候求出来的是`r2`

**Comment by shuxp** [comment]
> @shuxp 里面阴影部分的面积和一个ground truth框面积的overlap这个时候求出来的是`r2`

不能这么理解，如果这么理解的话，那么r3对应的iou是ground truth往外扩2*r的iou，r1、r2、r3都可以各有一个iou的解释

**Comment by gtwell** [comment]
@shuxp 本来就是这么理解的，r3确实就是往外扩的iou，因为关键点既可以在内部也可以在外部，取r1,r2,r3中间最小的就是保证最小iou要>=0.3。

**Comment by seeyouagain111** [comment]
早点上中文它不香吗，简单易懂

**Comment by ulanbator** [comment]
r1要如何理解呢？

**Comment by ulanbator** [comment]
> for `r2` you can calulate as following formula:
> ![6ff0f58b-74cc-4637-bbb9-1ea3aec26cdc](https://user-images.githubusercontent.com/27282516/59024894-81ba2a00-8885-11e9-85a3-6f861eda715f.jpg)

你好，我看完你的图还是有点困惑，首先图上为什么画的是正方形，不应该是以r为半径的圆弧吗？那么以r为半径的圆弧上，取哪两个点组成的矩形面积最小呢？
