### ISSUE TITLE
about network input size

### ISSUE THREAD

**Issue by xiaozhuka** [princeton-vl/CornerNet-Lite#51]
Hi @heilaw 
I use default input size 511 to train and test, test_scales is 1 and test_flipped is false.
When I evaluate, I find input image size is the original image size not the input size, is that correct? I think input image should be prepocessed to 512 before input into network to do inference.
[resize](https://github.com/princeton-vl/CornerNet-Lite/blob/master/core/test/cornernet.py#123)

./data/ch/val/JPEGImages/10016d000d0d6e0e8.jpg
torch.Size([3, 511, 767])
./data/ch/val/JPEGImages/1028c8000e8c388b9.jpg
torch.Size([3, 1023, 1407])
./data/ch/val/JPEGImages/1010cc000f912334d.jpg
torch.Size([3, 767, 1151])
./data/ch/val/JPEGImages/10034e000b214be47.jpg
torch.Size([3, 1023, 1407])
./data/ch/val/JPEGImages/101ae50008d3ac841.jpg
torch.Size([3, 4351, 3327])

**Comment by xiaozhuka** [comment]
Following the default settings of YOLOv3, we evaluate
YOLOv3 at 3 single image scales (320, 416 and 608). Similarly, we also evaluate CornerNet-Squeeze at different single scales (0.5, 0.6, 0.7, 0.8, 0.9, 1). CornerNet-Squeeze
achieves a better accuracy and efficiency (34.4% at 30ms)
trade-off than YOLOv3 (32.4% at 39ms).

I think this comparison is unfair. 
CornerNet-Squeeze scale 1.0 is the original image size or large than that.

**Comment by xiaozhuka** [comment]
Maybe this is an innovation.

**Comment by heilaw** [comment]
In CornerNet-Squeeze, we follow the inference procedure in CornerNet, where we use images at the original resolutions as the input to the network.

**Comment by xiaozhuka** [comment]
OK @heilaw . Thank you.
If input the original image to yolov3,  I think AP will be improved.
For CornerNet, the inference time will increase if the image resolution is large.

**Comment by pingqi** [comment]
@xiaozhuka @heilaw 
Have you test the forward of CornerNet-Squeeze is 30ms per image? But I test the result ,
CornerNet_Saccade	T4:420ms	1080Ti:205ms
CornerNet_Squeeze	T4:51ms	1080Ti:43ms

what is the condition of 30ms?
Thank you.
