### ISSUE TITLE
prediction boxes is wrong.

### ISSUE THREAD

**Issue by DeepTiming** [princeton-vl/CornerNet-Lite#8]
![demo_out_sca](https://user-images.githubusercontent.com/38682323/56467327-0543c700-6450-11e9-8edb-525e23451935.jpg)
![demo_out_squeeze](https://user-images.githubusercontent.com/38682323/56467328-0c6ad500-6450-11e9-810c-c57217531445.jpg)
First Image is CornerNet-Saccade result and second Image is CornerNet-squeeze result.

**Comment by DeepTiming** [comment]
Is there a problem in NMS process?

**Comment by heilaw** [comment]
CornerNet-Saccade estimates object locations via attention maps and detects object in a small region around each location. If the predicted attention maps are not sufficiently good, CornerNet-Saccade may miss an object or only see part of it. It seems to me that CornerNet-Saccade is not able to generate sufficiently good attention maps for this image.

More details about how the quality of the attention maps affects the performance of CornerNet-Saccade can be found in the experiment section of our [paper](https://arxiv.org/abs/1904.08900).

**Comment by DeepTiming** [comment]
Get it! Thank you very much! Good job!
