### ISSUE TITLE
Problem of use pretrained model, when i train own dataset

### ISSUE THREAD

**Issue by TTMRonald** [princeton-vl/CornerNet-Lite#83]
My own dataset have 13 categories, i modify the categories in json file.
But i get an error, when i run this file the train.py.

> RuntimeError: The shape of the mask [8, 13, 64, 64] at index 1 does not match the shape of the indexed tensor [8, 80, 64, 64] at index 1

The py_factory.py do not check loaded parameters and created model parameters.
` with open(pretrained_model, "rb") as f:
        params = torch.load(f)
        self.model.load_state_dict(params)`

I hope to get help from you.

**Comment by Lin427** [comment]
Have you solved this problem?

**Comment by Lin427** [comment]
@TTMRonald Have you solved this problem?

**Comment by TTMRonald** [comment]
@Lin427 I solved it.
You need modify the `load_pretrained_params ` of `py_factory.py` .
https://github.com/princeton-vl/CornerNet-Lite/blob/6a54505d830a9d6afe26e99f0864b5d06d0bbbaf/core/nnet/py_factory.py#L119

`      pre_params = torch.load(pretrained_model, map_location=lambda storage, loc: storage)
        pretrained_dict = pre_params
        model_dict = self.model.state_dict()
        # check loaded parameters and created model parameters
        for k, v in pretrained_dict.items():
            if k in model_dict:
                if pretrained_dict[k].shape != model_dict[k].shape:
                    print('Skip loading parameter {}, required shape{}, ' \
                          'loaded shape{}.'.format(
                        k, model_dict[k].shape, pretrained_dict[k].shape))
                    pretrained_dict[k] = model_dict[k]
            else:
                print('Drop parameter {}.'.format(k))
        # update and load parameters
        model_dict.update(pretrained_dict)
        self.model.load_state_dict(model_dict, strict=False)`

**Comment by veizgyauzgyauz** [comment]
And you need to modify the codes in $CornerNet-Lite$/core/models/CornerNet_Saccade.py:
1.
tl_heats = nn.ModuleList([self._pred_mod(80) for _ in range(stacks)])
→tl_heats = nn.ModuleList([self._pred_mod(13) for _ in range(stacks)])
2.
br_heats = nn.ModuleList([self._pred_mod(80) for _ in range(stacks)])
→br_heats = nn.ModuleList([self._pred_mod(13) for _ in range(stacks)])

**Comment by pingqi** [comment]
@TTMRonald ,I modify the py_factory.py,and If the code is as follows?Is it the indent right?
def load_pretrained_params(self, pretrained_model):
        print("loading from {}".format(pretrained_model))
        pre_params = torch.load(pretrained_model, map_location=lambda storage, loc: storage) 
        pretrained_dict = pre_params 
        model_dict = self.model.state_dict() 
        # check loaded parameters and created model parameters 
        for k, v in pretrained_dict.items(): 
            if k in model_dict: 
                if pretrained_dict[k].shape != model_dict[k].shape: 
                    print('Skip loading parameter {}, required shape{}, loaded shape{}.'.format( k, model_dict[k].shape, pretrained_dict[k].shape)) 
                    pretrained_dict[k] = model_dict[k] 
                else: 
                    print('Drop parameter {}.'.format(k)) 
        # update and load parameters 
        model_dict.update(pretrained_dict) 
        self.model.load_state_dict(model_dict, strict=False)

**Comment by pingqi** [comment]
@TTMRonald , I have modify the py_factory.py, Is it the indent right?
![捕获](https://user-images.githubusercontent.com/28916888/65016785-ab402280-d957-11e9-8d91-e23f2a19893a.PNG)
