### ISSUE TITLE
Can it work for Voc datasets?

### ISSUE THREAD

**Issue by tc-qaq** [princeton-vl/CornerNet-Lite#84]
I train CornerNet_Squeeze and CornerNet_Saccade for pascal voc datasets train: VOC2007trainval + VOC2012trainval,eval VOC2007test, and got map@50 = 0.5(Squeeze), 0.6(Saccade)
train para: batch_size=16, lr=0.00025, opt=Adam, train_iteration 100000

@heilaw

**Comment by tc-qaq** [comment]
sorry for this question

**Comment by tienthegainz** [comment]
@tc-qaq can you show me how to modify the dbs for VOC? Thank you
