### ISSUE TITLE
train cornernet-squeeze error

### ISSUE THREAD

**Issue by ZCDu** [princeton-vl/CornerNet-Lite#85]
Hey，can this cornernet trian at one 1080ti with RAM only 8G ?According to the train doc ,I get "AttributeError: 'NoneType' object has no attribute 'shape'", this makes me very confused.

**Comment by jiangkunkun1993** [comment]
HI ,I have the same problem as you( 'NoneType' object has no attribute 'shape'). my computer config only is 1060 .so can you tell your wechat account,mine is 18811396527

**Comment by sunshangyun** [comment]
First, I have trained the cornerNet-Squeeze successfully on only one TITAN X(12GB) with batchsize of 14.You just need to adjust the batchsize  in " CornerNet-Squeeze.json" to accommodate the number of GPUs that are available to you..
Second, make sure your image data dir is right in  " CornerNet-Squeeze.json -->data_dir" and "dbs\coco.py"

**Comment by pengyaru** [comment]
@sunshangyun hello，can I have your whole code and the content of  dataset's  json?

**Comment by sunshangyun** [comment]
@pengyaru give me your e-mail or QQ or wechat

**Comment by DEEPcong** [comment]
> First, I have trained the cornerNet-Squeeze successfully on only one TITAN X(12GB) with batchsize of 14.You just need to adjust the batchsize in " CornerNet-Squeeze.json" to accommodate the number of GPUs that are available to you..
> Second, make sure your image data dir is right in " CornerNet-Squeeze.json -->data_dir" and "dbs\coco.py"

hello, how did your result on training cornernet-squeeze compare to 34.2% and how much training loss when stop training ? 
Thx!

**Comment by sunshangyun** [comment]
My training result is not as good as the paper described when the loss is between 4 and 5

发自我的iPhone

在 2019年10月29日，18:09，DEEPcong <notifications@github.com> 写道：

﻿

First, I have trained the cornerNet-Squeeze successfully on only one TITAN X(12GB) with batchsize of 14.You just need to adjust the batchsize in " CornerNet-Squeeze.json" to accommodate the number of GPUs that are available to you..
Second, make sure your image data dir is right in " CornerNet-Squeeze.json -->data_dir" and "dbs\coco.py"

hello, how did your result on training cornernet-squeeze compare to 34.2% and how much training loss when stop training ?
Thx!

**Comment by chenxiaocong1225** [comment]
ok，thank you！




On 10/31/2019 16:34, sunshangyun wrote:
My training result is not as good as the paper described when the loss is between 4 and 5

发自我的iPhone

在 2019年10月29日，18:09，DEEPcong <notifications@github.com> 写道：

﻿

First, I have trained the cornerNet-Squeeze successfully on only one TITAN X(12GB) with batchsize of 14.You just need to adjust the batchsize in " CornerNet-Squeeze.json" to accommodate the number of GPUs that are available to you..
Second, make sure your image data dir is right in " CornerNet-Squeeze.json -->data_dir" and "dbs\coco.py"

hello, how did your result on training cornernet-squeeze compare to 34.2% and how much training loss when stop training ?
Thx!

**Comment by larklili** [comment]
> @pengyaru give me your e-mail or QQ or wechat

hello,i have the same error,and i have added the data_dir in xx.json.but it doesnt work.Can i have your whole code?thanks:)

**Comment by larklili** [comment]
@sunshangyun
