### ISSUE TITLE
Specify which GPU to use for DataParallel

### ISSUE THREAD

**Issue by dheerajpreddy** [princeton-vl/CornerNet-Lite#89]
Hi, I have 3 GPUs on my system but GPU0 is currently preoccupied. I only want to use GPU1 for the training of the network. However, when I pass device_ids=[1,2] when calling DataParallel, the network still attempts to use GPU0 and runs out of memory. How can I specify which particular GPU to use?
I tried changing the default allocation of device_ids inside the DataParallel class, but then I get an error that 'input' and 'weights' should be on the same device but device 1 is not the same as device 0.

Alternatively, can I not use DataParallel since I'm only using 1 GPU?

Thanks

**Comment by jg925** [comment]
How did you figure out how to do this? I've been having problems with CUDA trying to allocate memory to GPU0. (I'm also trying to use multiple GPUs.)
